import { generatePromptForPlan } from "./prompts";
import { runPlanAI } from "./providerRouter";
import { loadGameModel } from "@/lib/game-models";
import { parsePlanJson } from "./parsePlan";
import { RICH_PLAN_FORMAT_HINT } from "./rich-format-hint";
import { normalizePlan } from "./normalizePlan";

export async function generatePlan(input: {
  phase: string;
  zone: string;
  age: string;
  goalsAvailable?: number;
  principles?: string[];
  psychThemes?: string[];
  model?: "POSSESSION" | "PRESSING" | "TRANSITION" | "COACHAI";
  totalDurationMin?: number;
}) {
  // --- Load the correct model (defaults to CoachAI Balanced)
  const gm = await loadGameModel(input.model || "COACHAI");

  const modelContext = {
    id: gm.id,
    name: gm.name,
    philosophy: gm.philosophy,
    globalPrinciples: gm.globalPrinciples,
    agePolicies: gm.agePolicies,
    sessionGuidelines: gm.sessionGuidelines,
    planningNotes: gm.prompts?.planningNotes,
  };

  // --- Build prompt & append rich-format hint
  let prompt = generatePromptForPlan({ ...input, modelContext });
  prompt += "\n" + RICH_PLAN_FORMAT_HINT;

  // --- Run model provider (Claude/Gemini)
  const text = await runPlanAI(prompt);

  // --- Parse into JSON & normalize for UI
  const rawObj = parsePlanJson(text);
  const canonical = normalizePlan(rawObj, input.totalDurationMin, text);

    // Ensure summary exists
  if (!canonical.summary) {
    const firstLine = String(canonical.rationale || "").split(/\n+/)[0].trim();
    canonical.summary = firstLine || "Session overview: structured plan generated by CoachAI.";
  }
  return canonical;
}
